services:
  Zeroseven\Countries\Events\AlterTableDefinitionStatementsEvent:
    tags:
      - name: event.listener
        identifier: 'z7_country/add-fields'
        method: 'addCountryConfiguration'
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent
  Zeroseven\Countries\Events\ModifyHrefLangTagsEvent:
    tags:
      - name: event.listener
        identifier: 'z7_country/hreflang'
        after: 'typo3-seo/hreflangGenerator'
        event: TYPO3\CMS\Frontend\Event\ModifyHrefLangTagsEvent
  Zeroseven\Countries\Events\AfterFormEnginePageInitializedEvent:
    tags:
      - name: event.listener
        identifier: 'z7_country/form-engine'
        method: 'checkCountryAndLanguageSettings'
        event: TYPO3\CMS\Backend\Controller\Event\AfterFormEnginePageInitializedEvent
